version: '3.8'

services:
  # Redis for real-time memory coordination
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # ChromaDB for semantic memory search
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

  # Main application
  multi-llm-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - chromadb
    volumes:
      - ./experiments:/app/experiments
      - ./results:/app/results
      - ./memory_systems:/app/memory_systems
    environment:
      - REDIS_URL=redis://redis:6379
      - CHROMA_URL=http://chromadb:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env

  # Jupyter for analysis
  jupyter:
    build: .
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - ./results:/app/results
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  redis_data:
  chromadb_data:
